import turtle as trtl

painter = trtl.Turtle()
painter.turtlesize(4)
painter.pensize(5)
painter.forward(100)
painter.right(90)
painter.pencolor('blue')
painter.forward(300)
painter.right(90)
painter.pencolor('red')
painter.forward(300)
painter.right(90)
painter.pencolor('green')
painter.forward(300)
painter.penup()
painter.forward(200)
painter.pendown()
painter.pencolor('yellow')
painter.circle(50)
painter.right(90)
painter.forward(60)
painter.circle(80)
painter.right(90)
painter.forward(100)
painter.circle(20)